spring:
  autoconfigure:
    exclude:
      - com.google.cloud.spring.autoconfigure.pubsub.GcpPubSubAutoConfiguration
      - com.google.cloud.spring.autoconfigure.pubsub.GcpPubSubReactiveAutoConfiguration